// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/holders/holders.messages.proto

package grpc_holders_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// book definition
type Holder struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	HeldBooks            []string `protobuf:"bytes,6,rep,name=held_books,json=heldBooks,proto3" json:"held_books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Holder) Reset()         { *m = Holder{} }
func (m *Holder) String() string { return proto.CompactTextString(m) }
func (*Holder) ProtoMessage()    {}
func (*Holder) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc06025b2b95b8a7, []int{0}
}

func (m *Holder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Holder.Unmarshal(m, b)
}
func (m *Holder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Holder.Marshal(b, m, deterministic)
}
func (m *Holder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Holder.Merge(m, src)
}
func (m *Holder) XXX_Size() int {
	return xxx_messageInfo_Holder.Size(m)
}
func (m *Holder) XXX_DiscardUnknown() {
	xxx_messageInfo_Holder.DiscardUnknown(m)
}

var xxx_messageInfo_Holder proto.InternalMessageInfo

func (m *Holder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Holder) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Holder) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Holder) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Holder) GetHeldBooks() []string {
	if m != nil {
		return m.HeldBooks
	}
	return nil
}

func init() {
	proto.RegisterType((*Holder)(nil), "grpc.holders.v1.Holder")
}

func init() {
	proto.RegisterFile("proto/holders/holders.messages.proto", fileDescriptor_cc06025b2b95b8a7)
}

var fileDescriptor_cc06025b2b95b8a7 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xc8, 0xcf, 0x49, 0x49, 0x2d, 0x2a, 0x86, 0xd1, 0x7a, 0xb9, 0xa9, 0xc5, 0xc5,
	0x89, 0xe9, 0xa9, 0xc5, 0x7a, 0x60, 0x69, 0x21, 0xfe, 0xf4, 0xa2, 0x82, 0x64, 0x3d, 0x98, 0x64,
	0x99, 0xa1, 0x52, 0x27, 0x23, 0x17, 0x9b, 0x07, 0x98, 0x2b, 0xc4, 0xc7, 0xc5, 0x94, 0x99, 0x22,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0xc4, 0x94, 0x99, 0x22, 0x24, 0xcb, 0xc5, 0x95, 0x96, 0x59,
	0x54, 0x5c, 0x12, 0x9f, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0x04, 0x16, 0xe7, 0x04, 0x8b, 0xf8, 0x25,
	0xe6, 0xa6, 0x0a, 0x49, 0x73, 0x71, 0xe6, 0x24, 0xc2, 0x64, 0x99, 0xc1, 0xb2, 0x1c, 0x20, 0x01,
	0xb0, 0xa4, 0x08, 0x17, 0x6b, 0x6a, 0x6e, 0x62, 0x66, 0x8e, 0x04, 0x0b, 0x58, 0x02, 0xc2, 0x01,
	0x99, 0x98, 0x91, 0x9a, 0x93, 0x12, 0x9f, 0x94, 0x9f, 0x9f, 0x5d, 0x2c, 0xc1, 0xa6, 0xc0, 0x0c,
	0x32, 0x11, 0x24, 0xe2, 0x04, 0x12, 0x48, 0x62, 0x03, 0xbb, 0xd1, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x87, 0x55, 0x5c, 0x00, 0xcb, 0x00, 0x00, 0x00,
}
